# Generated by Django 2.0.5 on 2018-09-11 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180828_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('f9fbfd74-fd94-4ed0-9ce5-da8650f26568'), max_length=100),
        ),
    ]
