# Generated by Django 2.0.5 on 2018-09-12 18:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accommodation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationhosting',
            name='check_in',
            field=models.TimeField(blank=True, default=datetime.time(14, 30)),
        ),
        migrations.AddField(
            model_name='accommodationhosting',
            name='check_out',
            field=models.TimeField(blank=True, default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('23bdd463-02b3-454c-bb6c-d137f665a0c8'), max_length=100),
        ),
    ]
