# Generated by Django 2.0.5 on 2018-09-14 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180914_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('5277cfe4-1c85-4cc7-8102-3093f6c2381b'), max_length=100),
        ),
    ]
