# Generated by Django 2.1 on 2018-09-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review_booking'),
        ('api', '0009_auto_20180915_0753'),
    ]

    operations = [
    ]
