# Generated by Django 2.0.5 on 2018-09-20 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180920_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationhosting',
            name='guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('b1562ab8-a95f-46d9-8130-9e486e2fd468'), max_length=100),
        ),
    ]
