# Generated by Django 2.0.5 on 2018-09-20 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180920_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='id',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('9964adcf-72d6-44e4-b748-4765cddec9d7'), max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='accommodation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='true', serialize=False, to='api.Accommodation'),
        ),
    ]
