# Generated by Django 2.1.1 on 2018-09-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180915_1351'),
        ('api', '0014_merge_20180927_0819'),
    ]

    operations = [
    ]
