# Generated by Django 2.1.1 on 2018-09-28 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180927_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('0f5c3e32-14c3-4c37-a174-af923983db94'), max_length=100),
        ),
    ]
