# Generated by Django 2.1.1 on 2018-09-28 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180928_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('1f0da4fc-a572-4eed-b763-7acd1466f75f'), max_length=100),
        ),
    ]
