# Generated by Django 2.1.1 on 2018-09-28 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180928_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('b7bf3265-4bfd-4a19-97f6-e482502b8372'), max_length=100),
        ),
    ]
