# Generated by Django 2.1.1 on 2018-09-28 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180928_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('8ac82e9d-a77a-4ac6-9eed-836c1c70a829'), max_length=100),
        ),
    ]
