# Generated by Django 2.1.1 on 2018-09-28 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180928_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('6dcec7e2-0a4b-43d2-ad33-ab2fe8ca705b'), max_length=100),
        ),
    ]
