# Generated by Django 2.1.1 on 2018-10-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180928_0928'),
        ('api', '0021_auto_20180928_0638'),
    ]

    operations = [
    ]
