# Generated by Django 2.1.1 on 2018-10-05 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20181004_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='addr_city',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='addr_number',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='addr_state',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='addr_street',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('822956a6-0e67-4e90-b94f-bcad363471d8'), max_length=100),
        ),
    ]
