# Generated by Django 2.1.1 on 2018-10-05 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181005_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('1cd0bac6-1d1b-4318-8bde-c9e0b3a28aff'), max_length=100),
        ),
    ]
