# Generated by Django 2.1.1 on 2018-10-06 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181005_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('bb9e57e5-4fe2-4609-8921-a731810415a5'), max_length=100),
        ),
    ]
