# Generated by Django 2.1.1 on 2018-10-06 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181006_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('c0274b7d-f2f5-4bf4-a70d-ca84e5ba615c'), max_length=100),
        ),
    ]
