# Generated by Django 2.1.1 on 2018-10-06 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20181006_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('66b133a1-a951-4998-b0eb-e223fcb08fd2'), max_length=100),
        ),
    ]
