# Generated by Django 2.1.1 on 2018-10-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_auto_20181006_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='hasReply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='toHost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('52ca895a-753d-44d5-ae45-65d051c3ebf4'), max_length=100),
        ),
    ]
