# Generated by Django 2.1.1 on 2018-10-07 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181006_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('e4231d55-8682-4e47-9bbf-c63f32fdaad6'), max_length=100),
        ),
    ]
