# Generated by Django 2.1.1 on 2018-10-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20181006_0739'),
        ('api', '0030_auto_20181007_1408'),
    ]

    operations = [
    ]
