# Generated by Django 2.1.1 on 2018-10-08 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20181008_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('55497394-448e-4bd5-95e5-1b29f668a421'), max_length=100),
        ),
    ]
