# Generated by Django 2.1.1 on 2018-10-08 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20181008_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('de05c497-88d1-441e-b89c-929b2c609bc0'), max_length=100),
        ),
    ]
