# Generated by Django 2.1.1 on 2018-10-11 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20181008_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('f6df940f-405c-444d-b0c9-e6052d98a3b6'), max_length=100),
        ),
    ]
