# Generated by Django 2.1.1 on 2018-10-20 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20181016_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('a1dedd54-5a6f-4ea3-91b2-d1349dcf7f7a'), max_length=100),
        ),
    ]
