# Generated by Django 2.1.1 on 2018-10-20 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20181021_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('aa3658b1-3480-4e78-a532-0c8b101b1d9a'), max_length=100),
        ),
    ]
