# Generated by Django 2.0.5 on 2018-08-18 07:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.datetime.today)),
                ('date_end', models.DateField(default=datetime.datetime.today)),
                ('note', models.TextField(blank=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AccommodationHosting')),
            ],
        ),
    ]
