# Generated by Django 2.0.5 on 2018-08-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='entertainment',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='location',
        ),
    ]
