# Generated by Django 2.0.5 on 2018-08-19 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='addr_city',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='addr_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='addr_state',
            field=models.CharField(choices=[('NSW', 'NSW')], default='NSW', max_length=10),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='addr_street',
            field=models.CharField(default='dedault', max_length=100),
        ),
    ]
