# Generated by Django 2.0.5 on 2018-09-15 07:53

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180914_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_paymentDue',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('d4d2e393-aeb1-4537-b89e-7c59e731282a'), max_length=100),
        ),
    ]
