# Generated by Django 2.0.5 on 2018-09-20 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180918_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_free', models.TextField()),
                ('price', models.PositiveIntegerField(default=100)),
                ('guest', models.IntegerField(default=1)),
                ('location', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('6f746845-564e-4722-90d9-856def930e31'), max_length=100),
        ),
        migrations.AddField(
            model_name='search',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Accommodation'),
        ),
    ]
