# Generated by Django 2.1.1 on 2018-09-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180920_0843'),
        ('api', '0005_review_booking'),
    ]

    operations = [
    ]
