# Generated by Django 2.1.1 on 2018-09-28 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180928_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('ac32c58d-56fb-4f6c-8f26-c149df58a4df'), max_length=100),
        ),
    ]
