# Generated by Django 2.1.1 on 2018-10-06 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181006_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('6cd9d435-fd78-46b5-b985-f532d07ad9ba'), max_length=100),
        ),
    ]
