# Generated by Django 2.1.1 on 2018-10-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20181008_0633'),
        ('api', '0029_auto_20181008_0410'),
    ]

    operations = [
    ]
