# Generated by Django 2.1.1 on 2018-10-10 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20181008_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('16c28b5a-a191-4fc0-b0eb-ebe00839ce19'), max_length=100),
        ),
    ]
