# Generated by Django 2.1.1 on 2018-10-10 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20181010_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('a70c4fc1-fa7c-4bbc-aec8-dc7533db55c8'), max_length=100),
        ),
    ]
