# Generated by Django 2.1.1 on 2018-10-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20181011_0610'),
        ('api', '0036_auto_20181010_2105'),
    ]

    operations = [
    ]
