# Generated by Django 2.1.1 on 2018-10-16 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20181012_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='Accomodation_Type',
            field=models.CharField(choices=[('Room', 'Room'), ('Studio', 'Studio'), ('Apartment', 'Apartment'), ('House', 'House'), ('Villa', 'Villa')], default='House', max_length=100),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='title',
            field=models.CharField(default=uuid.UUID('f3dc1fe6-0797-43f1-a47a-02e8c9e3993c'), max_length=100),
        ),
    ]
